const strings = {
  PERSONAL_LOAN: "Personal Loan",
  LOAN_Price: "₹ 2,0,000",
  EMI: "EMI",
  EMI_Price: "₹ 9,500",
  EMI_DUES: "EMI Due ₹ 9,500",
  DUE_DAYS: "Due in 3 days",
  PERSENT: "10%",
  INTREST_RATE: "INTEREST RATE",
  YEARS: "5 Years",
  TENURE: "TENURE",
  DISBURSAL: "DISBURSAL DATE",
  DATE: "05 Jan, 2020",
  POS: "POS",
  POS_PRICE: "₹ 4,00,000",
  PL1: "PL1",
  PL2: "PL2",
  LOAN_LIMIT: "LOAN LIMIT",
  LIMIT: "₹ 10,00,000",
  NEED_MORE_MONEY: "Need more money?",
  AVAIL: "AVAIL MORE FROM YOUR LIMIT IN 5 MINS",
  AVAILED_LOAN: "AVAILED LOAN",
  AVAILABLE_LOAN_PRICE: "₹ 2,0,000",
  AVAILABLE: "AVAILABLE",
  HEY: "Hey ",
  USER: "Katen",
  ACTIVE: "You have 3 active Loans of",
  ACTIVE_LOAN: "₹ 4,00,000",
  LIMIT_AVAILABLE: "Limit Available",
  LIMIT_TOTAL: "₹ 6,00,000",
  AVAIL_NOW: "Avail Now",
  ACTIVE_LOANS: "Active Loans",
};
export default strings;
